name: slack
version: 1.1.0
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: |-
  Package for accessing and utilizing the Slack webhook API.
  Currently only works for 'incoming webhooks'
homepage: https://github.com/ChildrenOfUr/dart-slack
dependencies:
  http: "^0.11.2"
dev_dependencies:
  browser: any
